name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  build_environment:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./PlaywrightUsage
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Creating directory and user with docker-group
      run: |
        sudo  adduser --ingroup docker --disabled-password --gecos '' reporter &&  
         mkdir playwright-report && chmod a+wxr -R playwright-report/ && ls -l 
    - name: Build Dockerfile
      run: >
         docker build -t playwright .
    - name: Run tests in container
      run: |
         sudo -u reporter -s
         docker run -v $PWD/playwright-report/:/opt/playwright/playwright-report/  \
         -e PLAYWRIGHT_BROWSERS_PATH=/ms-playwright playwright
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: PlaywrightUsage/playwright-report/
        retention-days: 30
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: PlaywrightUsage/playwright-report/e2e_junit.xml
